/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.bean.Empresa;
import model.dao.EmpresaDAO;

/**
 *
 * @author biela
 */
public class TelaCadastroEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroEmpresa
     */
    public TelaCadastroEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadastroEmp = new javax.swing.JLabel();
        lblSenhaEmp = new javax.swing.JLabel();
        txtSenhaEmp = new javax.swing.JTextField();
        lblRazaoS1 = new javax.swing.JLabel();
        txtRazaoS1 = new javax.swing.JTextField();
        lblCnpj1 = new javax.swing.JLabel();
        txtCnpj1 = new javax.swing.JTextField();
        lblEmailEmp1 = new javax.swing.JLabel();
        txtEmailEmp1 = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Empresa");
        setResizable(false);
        getContentPane().setLayout(null);

        lblCadastroEmp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCadastroEmp.setForeground(new java.awt.Color(66, 141, 255));
        lblCadastroEmp.setText("CADASTRO EMPRESA");
        getContentPane().add(lblCadastroEmp);
        lblCadastroEmp.setBounds(280, 40, 250, 20);

        lblSenhaEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSenhaEmp.setForeground(new java.awt.Color(66, 141, 255));
        lblSenhaEmp.setText("Senha:");
        getContentPane().add(lblSenhaEmp);
        lblSenhaEmp.setBounds(210, 290, 50, 20);
        getContentPane().add(txtSenhaEmp);
        txtSenhaEmp.setBounds(210, 320, 370, 30);

        lblRazaoS1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRazaoS1.setForeground(new java.awt.Color(66, 141, 255));
        lblRazaoS1.setText("Razão Social:");
        getContentPane().add(lblRazaoS1);
        lblRazaoS1.setBounds(210, 80, 90, 20);
        getContentPane().add(txtRazaoS1);
        txtRazaoS1.setBounds(210, 110, 370, 30);

        lblCnpj1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCnpj1.setForeground(new java.awt.Color(66, 141, 255));
        lblCnpj1.setText("CNPJ:");
        getContentPane().add(lblCnpj1);
        lblCnpj1.setBounds(210, 150, 40, 20);
        getContentPane().add(txtCnpj1);
        txtCnpj1.setBounds(210, 180, 370, 30);

        lblEmailEmp1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmailEmp1.setForeground(new java.awt.Color(66, 141, 255));
        lblEmailEmp1.setText("E-mail:");
        getContentPane().add(lblEmailEmp1);
        lblEmailEmp1.setBounds(210, 220, 50, 20);
        getContentPane().add(txtEmailEmp1);
        txtEmailEmp1.setBounds(210, 250, 370, 30);

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(66, 141, 255));
        btnCadastrar.setText("Cadatrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(350, 380, 100, 30);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(66, 141, 255));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(700, 30, 75, 23);

        setSize(new java.awt.Dimension(823, 478));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        Empresa e = new Empresa();
        EmpresaDAO dao = new EmpresaDAO();
        
        e.setRs(txtRazaoS1.getText());
        e.setCnpj(txtCnpj1.getText());
        e.setEmail(txtEmailEmp1.getText());
        e.setSenha(txtSenhaEmp.getText());
        dao.create(e);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        TelaLoginEmpresa tela = new TelaLoginEmpresa();
        tela.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCadastroEmp;
    private javax.swing.JLabel lblCnpj1;
    private javax.swing.JLabel lblEmailEmp1;
    private javax.swing.JLabel lblRazaoS1;
    private javax.swing.JLabel lblSenhaEmp;
    private javax.swing.JTextField txtCnpj1;
    private javax.swing.JTextField txtEmailEmp1;
    private javax.swing.JTextField txtRazaoS1;
    private javax.swing.JTextField txtSenhaEmp;
    // End of variables declaration//GEN-END:variables
}
