/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.dao.EmpresaDAO;

/**
 *
 * @author biela
 */
public class TelaLoginEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form TelaLoginEmpresa
     */
    public TelaLoginEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmailEmpresa = new javax.swing.JLabel();
        lblSenhaEmpresa = new javax.swing.JLabel();
        txtEmailEmpresa = new javax.swing.JTextField();
        pfSenhaEmpresa = new javax.swing.JPasswordField();
        lblIconEmpresa = new javax.swing.JLabel();
        btnConfirmarEmp = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Empresa");
        setResizable(false);
        getContentPane().setLayout(null);

        lblEmailEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmailEmpresa.setForeground(new java.awt.Color(66, 141, 255));
        lblEmailEmpresa.setText("Email:");
        getContentPane().add(lblEmailEmpresa);
        lblEmailEmpresa.setBounds(230, 140, 50, 20);

        lblSenhaEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSenhaEmpresa.setForeground(new java.awt.Color(66, 141, 255));
        lblSenhaEmpresa.setText("Senha:");
        getContentPane().add(lblSenhaEmpresa);
        lblSenhaEmpresa.setBounds(230, 220, 50, 20);
        getContentPane().add(txtEmailEmpresa);
        txtEmailEmpresa.setBounds(230, 170, 360, 30);
        getContentPane().add(pfSenhaEmpresa);
        pfSenhaEmpresa.setBounds(230, 250, 360, 30);

        lblIconEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadiado.png"))); // NOI18N
        getContentPane().add(lblIconEmpresa);
        lblIconEmpresa.setBounds(360, 40, 96, 90);

        btnConfirmarEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfirmarEmp.setForeground(new java.awt.Color(66, 141, 255));
        btnConfirmarEmp.setText("Confirmar");
        btnConfirmarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarEmpActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarEmp);
        btnConfirmarEmp.setBounds(360, 360, 100, 30);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(66, 141, 255));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(690, 30, 72, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 141, 255));
        jLabel1.setText("cadastre sua empresa");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 290, 120, 16);

        setSize(new java.awt.Dimension(823, 478));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEmpActionPerformed
        
        EmpresaDAO dao = new EmpresaDAO();
        
        if(dao.checkLogin(txtEmailEmpresa.getText(), pfSenhaEmpresa.getText())) {
            TelaMenuEmpresa tela = new TelaMenuEmpresa();
            tela.setVisible(true);
            dispose();
            
        } else {
            JOptionPane.showMessageDialog(null, "Email ou Senha inválidos!");
        }
    }//GEN-LAST:event_btnConfirmarEmpActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        TelaCadastroEmpresa tela = new TelaCadastroEmpresa();
        tela.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        TelaLoginUsuario tela = new TelaLoginUsuario();
        tela.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarEmp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmailEmpresa;
    private javax.swing.JLabel lblIconEmpresa;
    private javax.swing.JLabel lblSenhaEmpresa;
    private javax.swing.JPasswordField pfSenhaEmpresa;
    private javax.swing.JTextField txtEmailEmpresa;
    // End of variables declaration//GEN-END:variables
}
